substitutions:
  i2csdapin: GPIO4
  i2csclpin: GPIO5

esphome:
  name: esp32c3ch340-2-2
  friendly_name: esp32c3ch340-2-2
  platformio_options:
#    board_upload.flash_size: 16MB
    board_build.flash_mode: dio
    board_build.flash_size: 4MB
    board_build.mcu: esp32c3

  includes:
    - wf183de_sensor.h
    
esp32:
  board: airm2m_core_esp32c3
  variant: ESP32C3 
  framework:
    type: arduino

# Enable logging
logger:
# level: error
# Enable Home Assistant API


network:
  enable_ipv6: true
  min_ipv6_addr_count: 2



captive_portal:
i2c:
  sda: ${i2csdapin}
  scl: ${i2csclpin}
  scan: True
  id: bus_a
  frequency: 200k



sensor:
  - platform: custom
    lambda: |-
      auto wf183de_sensor = new esphome::wf183de::WF183DESensor(10000);  // 10秒更新一次
      App.register_component(wf183de_sensor);
      return {wf183de_sensor->get_temperature_sensor(), wf183de_sensor->get_pressure_sensor()};
    sensors:
      - name: "WF183DE Temperature"
        unit_of_measurement: "°C"
        accuracy_decimals: 1
      - name: "WF183DE Pressure"
        unit_of_measurement: "kPa"
        accuracy_decimals: 2

        

